language: ruby
rvm:
- 2.2.3
services:
- postgresql
script:
- bundle exec rake db:test:prepare
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: PHYcJ/4Ye8t6rAq+IGVOIQORfqmzC12qj0JYiR7+o+Pn9k94ocCaLtYVM5IL/o0BM5AbZEl13RaXXSnaspSLzX79Q8zIzEk0lSs/nNPRByn/TtB1slK+lvHvh3/B7JDcYxI7nyTeUmX2iHB209j2l+inAem2D2T4XEshgiRTkzvH2PbwDUl+LCND0LRKSMjwFbRCHCRU8/5AhBePjReIbchxeelwDL8Zf0hc4f4ykGWD2ye8/IN1ZSpezjlpHS8FmQAEcjs3fHHcikDGbKK7HcSKyPlAbctnC+MYSgXZ0Fq1A0pres40ZqjltHGvSvVJNXujz90ov8q3u1GK/kGcjzwbStJqt/gjrb3hHd2vYesHA1Uqv9kVKq23RLlaYle6F7Qk6O11lwkcX/D2qPaHso9eudEzcJyFFN8/TQri1CQlU8wDhQUkQbni9fmwD16fKrwcWvpJbgxzOKKPsg3pbODJ7Pbw8cJQ1q7eKOtO1o428FxQ4b+GgBZJDEwjxgRGAlYrCLQxJNJJJWc1sAVIRCgyBWhax2nUM3OAdxgfpy/AXzebbTblzodkQzRQm+IRixodNDvrMxw526MnlG24qA1II8TBdwb6CBf9Pg04+fQQ58ah7jk/BlYhjEt5XGTiFJrtWK9AXjO04UStZQFarWQ2BN1GufvQQFWZuSrKuqo=
  app: jedi-chess
addons:
  code_climate:
    repo_token: dca006fe68b49b5af3797bb553dacb7e46feeba0da7bdc1f8fd670cd34e17cf1 bundle exec rake
